from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from ancova_ops.showcase import build_showcase_payload as _build_showcase_payload
from ancova_ops.showcase import render_showcase_markdown as _render_showcase_markdown

DEFAULT_OUTPUT_PATH = Path(".reasoned_ops/showcase/showcase.md")


def build_showcase_payload(
    *,
    seed: int = 2026,
    outcome_rows: int = 400,
    logged_rows: int = 1200,
    longitudinal_entities: int = 120,
    longitudinal_days: int = 600,
) -> dict[str, Any]:
    """Run the completed research workflows and assemble the canonical ReasonedOps payload."""

    payload = _build_showcase_payload(
        seed=seed,
        outcome_rows=outcome_rows,
        logged_rows=logged_rows,
        longitudinal_entities=longitudinal_entities,
        longitudinal_days=longitudinal_days,
    )
    payload["project_identity"]["canonical_name"] = "ReasonedOps"
    payload["project_identity"]["former_name"] = "ANCOVA Ops"
    payload["project_identity"]["rename_checkpoint"] = "v1.1.0"
    return payload


def render_showcase_markdown(payload: dict[str, Any]) -> str:
    """Render the compatibility implementation using the canonical ReasonedOps identity."""

    markdown = _render_showcase_markdown(payload)
    replacements = (
        ("# ANCOVA Ops v1.0 Portfolio Showcase", "# ReasonedOps v1.1 Portfolio Showcase"),
        ("ANCOVA Ops is not designed", "ReasonedOps is not designed"),
        ("generated by `ancova-showcase`", "generated by `reasoned-showcase`"),
        ("ANCOVA Ops reproducibly connects", "ReasonedOps reproducibly connects"),
        ("COMPLETED / FROZEN AT v1.0", "COMPLETED RESEARCH PROTOTYPE / RENAMED AT v1.1"),
    )
    for old, new in replacements:
        markdown = markdown.replace(old, new)
    return markdown


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate the ReasonedOps portfolio showcase.")
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument("--outcome-rows", type=int, default=400)
    parser.add_argument("--logged-rows", type=int, default=1200)
    parser.add_argument("--longitudinal-entities", type=int, default=120)
    parser.add_argument("--longitudinal-days", type=int, default=600)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    parser.add_argument("--json-output", type=Path)
    parser.add_argument("--json", action="store_true", help="Print the structured payload.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    payload = build_showcase_payload(
        seed=args.seed,
        outcome_rows=args.outcome_rows,
        logged_rows=args.logged_rows,
        longitudinal_entities=args.longitudinal_entities,
        longitudinal_days=args.longitudinal_days,
    )
    markdown = render_showcase_markdown(payload)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(markdown, encoding="utf-8")
    if args.json_output is not None:
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(
            json.dumps(payload, indent=2, sort_keys=True),
            encoding="utf-8",
        )

    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print(f"ReasonedOps showcase report written to {args.output}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
